### ISSUE TITLE
关于 AndroidX-supported， disable Jetifier

### ISSUE THREAD

**Issue by boboqun** [lihangleo2/ShadowLayout#147]
Task :app:checkJetifier
The following libraries used by project ':app' depend on legacy support libraries. To disable Jetifier, you will need to use AndroidX-supported versions of these libraries.
	com.github.lihangleo2:ShadowLayout:3.2.4 (Project ':app', configuration 'debugRuntimeClasspath' -> com.github.lihangleo2:ShadowLayout:3.2.4 -> com.android.support:appcompat-v7:28.0.0)

**Comment by lihangleo2** [comment]
在AndroidX里如何使用？根目录下找到gradle的配置文件gradle.properties里加上以下2句代码：
android.useAndroidX=true
android.enableJetifier=true
看清楚文档，兄弟。非常感谢你的支持

**Comment by boboqun** [comment]
嗯。不是这个意思。是as推荐关闭Jetifier 就是推荐不要再依赖 com.android.support:appcompat-v7:28.0.0

**Comment by lihangleo2** [comment]
这是官方推荐的方式。把你第三方依赖，在cradle编译的时候转成AndroidX使用        
            
                
                    
                            
                                
                            
                            
                                李航
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- 回复的原邮件 ***@***.***>发送日期2022年05月17日 15:54 ***@***.***> ***@***.***>,State ***@***.***>主题Re: [lihangleo2/ShadowLayout] 关于 AndroidX-supported， disable Jetifier (Issue #147)

嗯。不是这个意思。是as推荐关闭Jetifier 就是推荐不要再依赖 com.android.support:appcompat-v7:28.0.0



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/lihangleo2/ShadowLayout/issues/147#issuecomment-1128536344",

"url": "https://github.com/lihangleo2/ShadowLayout/issues/147#issuecomment-1128536344",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by boboqun** [comment]
嗯那 请问这个库怎么按推荐方式转换成 ‘AndroidX-supported version’ ？

**Comment by lihangleo2** [comment]
兄弟，已经告诉你方式了啊……加上配置之后build下        
            
                
                    
                            
                                
                            
                            
                                李航
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- 回复的原邮件 ***@***.***>发送日期2022年05月17日 16:21 ***@***.***> ***@***.***>,State ***@***.***>主题Re: [lihangleo2/ShadowLayout] 关于 AndroidX-supported， disable Jetifier (Issue #147)

嗯那 请问这个库怎么按推荐方式转换成 ‘AndroidX-supported version’ ？



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/lihangleo2/ShadowLayout/issues/147#issuecomment-1128565961",

"url": "https://github.com/lihangleo2/ShadowLayout/issues/147#issuecomment-1128565961",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by boboqun** [comment]
啊，，，你可能没理解我的意思，，，
他这报错的意思大概是需要支持 androidx 的第三方库，目的是把 android.enableJetifier 改为 false
